### ISSUE TITLE
Bug in Setup Wizard

### ISSUE THREAD

**Issue by timstoffel** [PCJones/MediathekArr#18]
I am trying to test the beta and have taken the setup from here (https://github.com/PCJones/MediathekArr/releases/tag/v1.0-beta).

I have deleted all other previous Mediathekarr configurations.

My procedure:

- Started Docker container via Compose.
- Wizard has reported
  - Folder specified
  - Tried to configure the Sonarr client

**Relevant section from the compose file**

```
name: unraid_env

services:
  mediathekarr:
    image: pcjones/mediathekarr:beta
    restart: unless-stopped
    container_name: mediathekarr
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin
      # You can use the web interface at http://localhost:5007 to configure the following settings
      # Alternatively, you can set them here
      #- DOWNLOAD_INCOMPLETE_PATH=/data/mediathek/incomplete # Path to incomplete downloads
      #- DOWNLOAD_COMPLETE_PATH=/data/mediathek/complete # Path to complete downloads"

      # Only change this if you are hosting your own API. Not needed for 99% of users
      MEDIATHEKARR_API_BASE_URL: https://mediathekarr.pcjones.de/api/v1
    volumes:
      - /mnt/user/appdata/mediathekarr:/app/config
      - /mnt/user/media_data/mediathek/complete:/data/mediathek/complete
      - /mnt/user/media_data/mediathek/incomplete:/data/mediathek/incomplete
    ports:
      - "5007:5007" # Port on the right side can be changed to any value you like
    networks:
      proxy_net:
        aliases:
          - mediathekarr

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    depends_on:
      prowlarr:
        condition: service_started
      proxy:
        condition: service_healthy
    volumes:
      - /mnt/user/media_data/:/data
      - /mnt/user/appdata/radarr:/config
    environment:
      TZ: Europe/Berlin
      UMASK: 0
      PUID: 99
      PGID: 100
    networks:
      proxy_net:
        aliases:
          - radarr
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7878/ping" ]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 10s

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    depends_on:
      prowlarr:
        condition: service_started
      proxy:
        condition: service_healthy
    volumes:
      - /mnt/user/media_data/:/data
      - /mnt/user/appdata/binhex-sonarr:/config
    environment:
      TZ: Europe/Berlin
      UMASK: 0
      PUID: 99
      PGID: 100
    networks:
      proxy_net:
        aliases:
          - sonarr
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8989/ping" ]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 10s

networks:
  proxy_net:
    name: proxy_net
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: 172.30.255.0/24
```

**Screenshot**
![Image](https://github.com/user-attachments/assets/4b888c10-381a-4375-a815-08d0e0dfd51a)

**Log Web**
```
Status:
Verifying Sonarr details...

Sonarr details verified successfully.

Fetching existing Sabnzbd clients...

Existing clients found. Please select one.

Proceeding to create a new client...

Starting client settings test...

Test failed: Unknown error

Testing with alternate host: mediathekarr...

Test failed with alternate host.

Retrying with updated host (mediathekarr) and port (5007)...

Starting client settings test...

Test successful! Client settings are valid.

Failed to update client: Unknown error

Failed to update client: Unknown error

Starting client settings test...

Test successful! Client settings are valid.

Failed to update client: Unknown error
```

**Developer Console**

![Image](https://github.com/user-attachments/assets/33e66b19-b75e-4238-afd8-654722ecd232)

![Image](https://github.com/user-attachments/assets/c0a75933-503c-4054-92ca-bc7108d61430)

**Log Docker**
```
Mediathekarr: Starting with UID: 1000, GID: 1000
Adjusting ownership for mounted volumes...
Checking mounted directory: /app/config
Setting ownership for /app/config
Checking mounted directory: /data/mediathek/complete
Setting ownership for /data/mediathek/complete
Checking mounted directory: /data/mediathek/incomplete
Setting ownership for /data/mediathek/incomplete
[MediathekArrDownloader] info: Program - Config path set to: /app/config/mediathekarr.json
[MediathekArrDownloader] warn: Program - Using default incomplete path: /data/mediathek/incomplete
[MediathekArrDownloader] warn: Program - Using default complete path: /data/mediathek/complete
[MediathekArrDownloader] warn: Program - Attention!
[MediathekArrDownloader] warn: Program - Configuration file was not found. Please visit http://localhost:5007/ to setup MediathekArr.
[MediathekArrDownloader] warn: Program - Alternatively use environment variables (see https://github.com/PCJones/MediathekArr).
[MediathekArrDownloader] warn: Program - MediathekArr will use default values:
[MediathekArrServer] info: MediathekArrServer.Services.RulesetBackgroundService - Starting ruleset update at 01/17/2025 10:55:11
[MediathekArrDownloader] info: Program - MediathekArr Configuration: {
  "IncompletePath": "/data/mediathek/incomplete",
  "CompletePath": "/data/mediathek/complete"
}
[MediathekArrServer] info: MediathekArrLib.Utilities.HttpClientLoggingHandler - Start processing HTTP request GET https://mediathekarr.pcjones.de/metadata/api/rulesets.php?page=1
[MediathekArrDownloader] info: MediathekArrDownloader.Services.DownloadService - mkvmerge found in PATH at /usr/bin/mkvmerge.
[MediathekArrServer] warn: Microsoft.AspNetCore.Server.Kestrel - Overriding address(es) 'http://*:8080'. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.
[MediathekArrDownloader] warn: Microsoft.AspNetCore.Server.Kestrel - Overriding address(es) 'http://*:8080'. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.
[MediathekArrServer] info: Microsoft.Hosting.Lifetime - Now listening on: http://[::]:5008
[MediathekArrDownloader] info: Microsoft.Hosting.Lifetime - Now listening on: http://[::]:5007
[MediathekArrServer] info: Microsoft.Hosting.Lifetime - Application started. Press Ctrl+C to shut down.
[MediathekArrServer] info: Microsoft.Hosting.Lifetime - Hosting environment: Production
[MediathekArrServer] info: Microsoft.Hosting.Lifetime - Content root path: /app/MediathekArrServer
[MediathekArrDownloader] info: Microsoft.Hosting.Lifetime - Application started. Press Ctrl+C to shut down.
[MediathekArrDownloader] info: Microsoft.Hosting.Lifetime - Hosting environment: Production
[MediathekArrDownloader] info: Microsoft.Hosting.Lifetime - Content root path: /app/MediathekArrDownloader
[MediathekArrServer] info: MediathekArrLib.Utilities.HttpClientLoggingHandler - Finished processing HTTP request GET https://mediathekarr.pcjones.de/metadata/api/rulesets.php?page=1
[MediathekArrServer] info: MediathekArrServer.Services.RulesetBackgroundService - Ruleset update completed successfully at 01/17/2025 10:55:11
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=queue&start=0&limit=0&category=tv&apikey=x&output=json
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=history&start=0&limit=60&category=tv&apikey=x&output=json
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=queue&start=0&limit=0&category=tv&apikey=x&output=json
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=history&start=0&limit=60&category=tv&apikey=x&output=json
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=queue&start=0&limit=0&category=movies&apikey=x&output=json
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=history&start=0&limit=60&category=movies&apikey=x&output=json
[MediathekArrDownloader] info: Program - Incoming Request: GET /download
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/css/queue.css
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/img/logo.png
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/js/queue.js
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=queue
[MediathekArrDownloader] info: Program - Incoming Request: GET /favicon.ico
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=queue
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=queue
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=queue&start=0&limit=0&category=tv&apikey=x&output=json
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=history&start=0&limit=60&category=tv&apikey=x&output=json
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=queue
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=queue
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=queue
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=queue
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=queue
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/config
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=queue
[MediathekArrDownloader] info: Program - Incoming Request: POST /download/config
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=queue
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/wizard.html
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/css/wizard.css
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/js/wizard.js
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=queue&start=0&limit=0&category=tv&apikey=x&output=json
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=history&start=0&limit=60&category=tv&apikey=x&output=json
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=queue&start=0&limit=0&category=tv&apikey=x&output=json
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=history&start=0&limit=60&category=tv&apikey=x&output=json
[MediathekArrDownloader] info: Program - Incoming Request: GET /wizard/downloadclients?sonarrHost=http%3A%2F%2Fsonarr%3A8989&apiKey=44d749243ba04ae2b1ff0539af31bc3d
[MediathekArrDownloader] info: System.Net.Http.HttpClient.Default.LogicalHandler - Start processing HTTP request GET http://sonarr:8989/api/v3/downloadclient
[MediathekArrDownloader] info: System.Net.Http.HttpClient.Default.ClientHandler - Sending HTTP request GET http://sonarr:8989/api/v3/downloadclient
[MediathekArrDownloader] info: System.Net.Http.HttpClient.Default.ClientHandler - Received HTTP response headers after 73.9437ms - 200
[MediathekArrDownloader] info: System.Net.Http.HttpClient.Default.LogicalHandler - End processing HTTP request after 83.3736ms - 200
[MediathekArrDownloader] info: Program - Incoming Request: GET /wizard/downloadclients?sonarrHost=http%3A%2F%2Fsonarr%3A8989&apiKey=44d749243ba04ae2b1ff0539af31bc3d
[MediathekArrDownloader] info: System.Net.Http.HttpClient.Default.LogicalHandler - Start processing HTTP request GET http://sonarr:8989/api/v3/downloadclient
[MediathekArrDownloader] info: System.Net.Http.HttpClient.Default.ClientHandler - Sending HTTP request GET http://sonarr:8989/api/v3/downloadclient
[MediathekArrDownloader] info: System.Net.Http.HttpClient.Default.ClientHandler - Received HTTP response headers after 5.0858ms - 200
[MediathekArrDownloader] info: System.Net.Http.HttpClient.Default.LogicalHandler - End processing HTTP request after 5.15ms - 200
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=queue&start=0&limit=0&category=tv&apikey=x&output=json
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=history&start=0&limit=60&category=tv&apikey=x&output=json
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=queue&start=0&limit=0&category=movies&apikey=x&output=json
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=history&start=0&limit=60&category=movies&apikey=x&output=json
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=queue&start=0&limit=0&category=movies&apikey=x&output=json
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=history&start=0&limit=60&category=movies&apikey=x&output=json
[MediathekArrDownloader] info: Program - Incoming Request: POST /wizard/downloadclient/test?sonarrHost=http%3A%2F%2Fsonarr%3A8989&apiKey=44d749243ba04ae2b1ff0539af31bc3d
[MediathekArrDownloader] info: System.Net.Http.HttpClient.Default.LogicalHandler - Start processing HTTP request POST http://sonarr:8989/api/v3/downloadclient/test
[MediathekArrDownloader] info: System.Net.Http.HttpClient.Default.ClientHandler - Sending HTTP request POST http://sonarr:8989/api/v3/downloadclient/test
[MediathekArrDownloader] info: System.Net.Http.HttpClient.Default.ClientHandler - Received HTTP response headers after 419.4796ms - 400
[MediathekArrDownloader] info: System.Net.Http.HttpClient.Default.LogicalHandler - End processing HTTP request after 419.558ms - 400
[MediathekArrDownloader] info: Program - Incoming Request: POST /wizard/downloadclient/test?sonarrHost=http%3A%2F%2Fsonarr%3A8989&apiKey=44d749243ba04ae2b1ff0539af31bc3d
[MediathekArrDownloader] info: System.Net.Http.HttpClient.Default.LogicalHandler - Start processing HTTP request POST http://sonarr:8989/api/v3/downloadclient/test
[MediathekArrDownloader] info: System.Net.Http.HttpClient.Default.ClientHandler - Sending HTTP request POST http://sonarr:8989/api/v3/downloadclient/test
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=version&apikey=x&output=json
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=get_config&apikey=x&output=json
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=get_config&apikey=x&output=json
[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=get_config&apikey=x&output=json
[MediathekArrDownloader] info: System.Net.Http.HttpClient.Default.ClientHandler - Received HTTP response headers after 61.0623ms - 200
[MediathekArrDownloader] info: System.Net.Http.HttpClient.Default.LogicalHandler - End processing HTTP request after 61.1611ms - 200
[MediathekArrDownloader] info: Program - Incoming Request: PUT /wizard/downloadclient/2?sonarrHost=http%3A%2F%2Fsonarr%3A8989&apiKey=44d749243ba04ae2b1ff0539af31bc3d
[MediathekArrDownloader] info: System.Net.Http.HttpClient.Default.LogicalHandler - Start processing HTTP request PUT http://sonarr:8989/api/v3/downloadclient/2
[MediathekArrDownloader] info: System.Net.Http.HttpClient.Default.ClientHandler - Sending HTTP request PUT http://sonarr:8989/api/v3/downloadclient/2
[MediathekArrDownloader] info: System.Net.Http.HttpClient.Default.ClientHandler - Received HTTP response headers after 9.3825ms - 404
[MediathekArrDownloader] info: System.Net.Http.HttpClient.Default.LogicalHandler - End processing HTTP request after 9.4359ms - 404
[MediathekArrDownloader] info: Program - Incoming Request: PUT /wizard/downloadclient/2?sonarrHost=http%3A%2F%2Fsonarr%3A8989&apiKey=44d749243ba04ae2b1ff0539af31bc3d
[MediathekArrDownloader] info: System.Net.Http.HttpClient.Default.LogicalHandler - Start processing HTTP request PUT http://sonarr:8989/api/v3/downloadclient/2
[MediathekArrDownloader] info: System.Net.Http.HttpClient.Default.ClientHandler - Sending HTTP request PUT http://sonarr:8989/api/v3/downloadclient/2
[MediathekArrDownloader] info: System.Net.Http.HttpClient.Default.ClientHandler - Received HTTP response headers after 1.6418ms - 404
[MediathekArrDownloader] info: System.Net.Http.HttpClient.Default.LogicalHandler - End processing HTTP request after 1.6937ms - 404
```
