### ISSUE TITLE
Can't connect to SABnzbd

### ISSUE THREAD

**Issue by JHA-2021** [PCJones/MediathekArr#2]
Running the docker on unraid. When I try to create a download client by using/modifying the SABnzdb Downloader, it says "Test was aborted due to an error: Unable to connect to SABnzdb, An error occurred while sending the request." when I use my Host_IP together with port 5007 (bridge mode). When I try "localhost" it refuses connection...

**Comment by PCJones** [comment]
Can you try updating the image?

**Comment by Joly0** [comment]
Hey, i am getting the same error, i just pulled the image

**Comment by JHA-2021** [comment]
@PCJones I just updated...no change

**Comment by PCJones** [comment]
Please delete the app and do a clean reinstallation. If the error persists please share your docker compose / unraid template

**Comment by Joly0** [comment]
For me its still not working
My compose looks like this (i stripped some services):
```
services:
  gluetunvpn:
    image: qmcgaw/gluetun
    container_name: gluetunvpn
    environment:
      - TZ=${TZ}
      - HOST_OS=${HOST_OS}
      - HOST_HOSTNAME=${HOST_HOSTNAME}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - VPN_INTERFACE=tun0
      - WIREGUARD_PRIVATE_KEY=
      - WIREGUARD_ADDRESSES=
      - SERVER_COUNTRIES=
      - DOT_PROVIDERS=quad9
      - BLOCK_MALICIOUS=on
      - BLOCK_SURVEILLANCE=on
      - BLOCK_ADS=on
      - HTTPPROXY=off
      - SHADOWSOCKS=off
      - HEALTH_TARGET_ADDRESS=github.com:443
      - PUBLICIP_FILE=/gluetun/ip
      - UPDATER_PERIOD=${UPDATE_PERIOD}
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      net.unraid.docker.icon: 'https://raw.githubusercontent.com/qdm12/gluetun/master/doc/logo_256.png'
    ports:
      - '8465:8888/tcp'
      - '8686:8686/tcp'
      - '8000:8000/tcp'
      - '7809:8080/tcp' # SabNZBd WebUI
      - '8989:8989/tcp' # Sonarr WebUI
      - '7878:7878/tcp' # Radarr WebUI
      - '9696:9696/tcp' # Prowlarr WebUI
      - '5007:5007/tcp' # Mediathekarr WebUI
    volumes:
      - /mnt/cache/appdata/gluetun:/gluetun:rw
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - TZ=${TZ}
      - HOST_OS=${HOST_OS}
      - HOST_HOSTNAME=${HOST_HOSTNAME}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
    labels:
      net.unraid.docker.webui: 'http://${HOST_IP}:7809'
      net.unraid.docker.icon: 'https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/sabnzbd-logo.png'
    volumes:
      - ${DATA_PATH}/usenet:/data/usenet:rw
      - /mnt/cache/appdata/sabnzbd:/config:rw
    depends_on:
      - gluetunvpn
    network_mode: "service:gluetunvpn"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - TZ=${TZ}
      - HOST_OS=${HOST_OS}
      - HOST_HOSTNAME=${HOST_HOSTNAME}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
    labels:
      net.unraid.docker.webui: 'http://${HOST_IP}:9696'
      net.unraid.docker.icon: 'https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/prowlarr-logo.png'
    volumes:
      - /mnt/cache/appdata/prowlarr:/config:rw
    depends_on:
      - gluetunvpn
      - sabnzbd
    network_mode: "service:gluetunvpn"
    restart: unless-stopped
  
  umlautadaptarr:
    image: pcjones/umlautadaptarr:latest
    container_name: umlautadaptarr
    environment:
      - TZ=Europe/Berlin
      - SONARR__ENABLED=True
      - SONARR__HOST=http://localhost:8989
      - SONARR__APIKEY=aa5ea1c1dcca459f9ed9b7c23011dc02
      - RADARR__ENABLED=True
      - RADARR__HOST=http://localhost:7878
      - RADARR__APIKEY=e3b7454eeafb4320bd861c354ae7b374
      - READARR__ENABLED=false
      - READARR__HOST=http://localhost:8787
      - READARR__APIKEY=APIKEY
      - LIDARR__ENABLED=false
      - LIDARR__HOST=http://localhost:8686
      - LIDARR__APIKEY=APIKEY
    labels:
      net.unraid.docker.icon: 'https://raw.githubusercontent.com/tschoerk/unraid-templates/main/umlautadaptarr/umlaute.png'
    depends_on:
      - gluetunvpn
      - sabnzbd
      - prowlarr
    network_mode: "service:gluetunvpn"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - TZ=${TZ}
      - HOST_OS=${HOST_OS}
      - HOST_HOSTNAME=${HOST_HOSTNAME}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - DOCKER_MODS=linuxserver/mods:radarr-striptracks
      - STRIPTRACKS_ARGS=--audio :ger:eng:und --subs :ger:eng
    labels:
      net.unraid.docker.webui: 'http://${HOST_IP}:7878'
      net.unraid.docker.icon: 'https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/radarr-logo.png'
    volumes:
      - ${DATA_PATH}:/data:rw
      - /mnt/cache/appdata/radarr:/config:rw
    depends_on:
      - gluetunvpn
      - prowlarr
      - sabnzbd
    network_mode: "service:gluetunvpn"
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - TZ=${TZ}
      - HOST_OS=${HOST_OS}
      - HOST_HOSTNAME=${HOST_HOSTNAME}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - DOCKER_MODS=linuxserver/mods:radarr-striptracks
      - STRIPTRACKS_ARGS=--audio :ger:eng:und --subs :ger:eng
    labels:
      net.unraid.docker.webui: 'http://${HOST_IP}:8989'
      net.unraid.docker.icon: 'https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/sonarr-logo.png'
    volumes:
      - ${DATA_PATH}:/data:rw
      - /mnt/cache/appdata/sonarr:/config:rw
    depends_on:
      - gluetunvpn
      - prowlarr
      - sabnzbd
    network_mode: "service:gluetunvpn"
    restart: unless-stopped

  mediathekarr:
    image: pcjones/mediathekarr:latest
    container_name: mediathekarr
    environment:
      - TZ=Europe/Berlin
      - DOWNLOAD_FOLDER_PATH_MAPPING=/downloads/completed # Change right side for correct path mapping
    labels:
      net.unraid.docker.webui: 'http://${HOST_IP}:5007'
      net.unraid.docker.icon: 'https://private-user-images.githubusercontent.com/377223/382745210-0e3b6d3a-214b-4382-9111-4b5c001ffc00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMDAxNTcsIm5iZiI6MTczMDk5OTg1NywicGF0aCI6Ii8zNzcyMjMvMzgyNzQ1MjEwLTBlM2I2ZDNhLTIxNGItNDM4Mi05MTExLTRiNWMwMDFmZmMwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QxNzE3MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNDFhZjEwMTNjNzMwNDJhZGViOWYxNmJlYWEwNGZhOWJjODMxZDQ2YTIyOWRiZGYzODQyMGRiYmM1M2UxMGYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RMSkwGfFr8llspNaHcd9fjjRqNOlsCEMTwd-noerCgk'
    volumes:
      - ${DATA_PATH}/mediathekarr:/app/downloads      # Change left side to your temp download folder location
    depends_on:
      - gluetunvpn
      - prowlarr
      - sabnzbd
    restart: unless-stopped
```
