### ISSUE TITLE
invalid user: 'appuser:appgroup'

### ISSUE THREAD

**Issue by PinBob100** [PCJones/MediathekArr#29]
Hi,

first of all thanks alot for your work.

I ran the docker composer for the beta version. I get the errors below. I could not find a solution in other posts. What am I missing? Thanks! (UID, GID are correct btw).

```
2025/02/10 12:02:25 | stderr | error: failed switching to "appuser": unable to find user appuser: no matching entries in passwd file
2025/02/10 12:02:25 | stderr | chown: invalid user: 'appuser:appgroup'
2025/02/10 12:02:25 | stdout | Setting ownership for /data/mediathek/incomplete
2025/02/10 12:02:25 | stdout | Checking mounted directory: /data/mediathek/incomplete
2025/02/10 12:02:25 | stderr | chown: invalid user: 'appuser:appgroup'
2025/02/10 12:02:25 | stdout | Setting ownership for /data/mediathek/complete
2025/02/10 12:02:25 | stdout | Checking mounted directory: /data/mediathek/complete
2025/02/10 12:02:25 | stderr | chown: invalid user: 'appuser:appgroup'
2025/02/10 12:02:25 | stdout | Setting ownership for /app/config
2025/02/10 12:02:25 | stdout | Checking mounted directory: /app/config
2025/02/10 12:02:25 | stdout | Adjusting ownership for mounted volumes...
2025/02/10 12:02:25 | stderr | chown: invalid user: 'appuser:appgroup'
2025/02/10 12:02:25 | stderr | useradd: group 'appgroup' does not exist
2025/02/10 12:02:25 | stderr | groupadd: GID '100' already exists
2025/02/10 12:02:25 | stdout | Mediathekarr: Starting with UID: 1030, GID: 100
2025/02/10 12:01:17 | stderr | error: failed switching to "appuser": unable to find user appuser: no matching entries in passwd file
2025/02/10 12:01:17 | stderr | chown: invalid user: 'appuser:appgroup'
2025/02/10 12:01:17 | stdout | Setting ownership for /data/mediathek/complete
2025/02/10 12:01:17 | stdout | Checking mounted directory: /data/mediathek/complete
2025/02/10 12:01:17 | stderr | chown: invalid user: 'appuser:appgroup'
2025/02/10 12:01:17 | stderr | chown: invalid user: 'appuser:appgroup'
2025/02/10 12:01:17 | stdout | Setting ownership for /data/mediathek/incomplete
2025/02/10 12:01:17 | stdout | Checking mounted directory: /data/mediathek/incomplete
2025/02/10 12:01:17 | stdout | Setting ownership for /app/config
2025/02/10 12:01:17 | stdout | Checking mounted directory: /app/config
2025/02/10 12:01:17 | stdout | Adjusting ownership for mounted volumes...
2025/02/10 12:01:17 | stderr | chown: invalid user: 'appuser:appgroup'
2025/02/10 12:01:17 | stderr | useradd: group 'appgroup' does not exist
2025/02/10 12:01:17 | stderr | groupadd: GID '100' already exists
2025/02/10 12:01:17 | stdout | Mediathekarr: Starting with UID: 1030, GID: 100
```

**Comment by PCJones** [comment]
Never seen that before. Can you share your docker compose file?

**Comment by PinBob100** [comment]
Thanks for the quick reply. Here is the docker-composer.yml:

```
services:
  mediathekarr:
    image: pcjones/mediathekarr:beta
    restart: unless-stopped
    container_name: mediathekarr
    environment:
      - PUID=1030
      - PGID=100
      - TZ=Europe/Berlin
      # You can use the web interface at http://localhost:5007 to configure the following settings
      # Alternatively, you can set them here
      - DOWNLOAD_INCOMPLETE_PATH=/data/mediathek/incomplete # Path to incomplete downloads
      - DOWNLOAD_COMPLETE_PATH=/data/mediathek/complete # Path to complete downloads"

      # Only change this if you are hosting your own API. Not needed for 99% of users
      - MEDIATHEKARR_API_BASE_URL=https://mediathekarr.pcjones.de/api/v1
    volumes:
      - /volume1/docker/mediathekarr:/app/config
      - /volume1/media/Mediathek/complete:/data/mediathek/complete
      - /volume1/media/Mediathek/incomplete:/data/mediathek/incomplete
    ports:
      - "127.0.0.1:5007:5007" # Port on the right side can be changed to any value you like
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
```
