### ISSUE TITLE
sonarr: finished episodes not coped to destination folder?

### ISSUE THREAD

**Issue by prankousky** [PCJones/MediathekArr#42]
Hi,

Am I doing something wrong, or is this expected behavior? I set this up according to the docs, I am able to find episodes via `sonarr`, but once they are downloaded, they stay where they had been downloaded to. No automatic moving to my tv collection folder.

This is the relevant part of my `docker-compose.yml`:

```yaml
  mediathekarr:
    image: pcjones/mediathekarr:latest
    container_name: mediathekarr
    environment:
      - TZ=Europe/Berlin
      - DOWNLOAD_FOLDER_PATH_MAPPING=/app/downloads # Change right side for correct path mapping
    volumes:
      - /volume1/secure/downloads/sabnzbd/complete/mediathek:/app/downloads      # Change left side to your temp download folder location
    ports:
      - "127.0.0.1:5007:5007"                             # Port on the right side can be changed to any value you like
    restart: unless-stopped
```

Example show `Erzgebirgskrimi` has automatically been set up like this

![Image](https://github.com/user-attachments/assets/791d0e90-b624-4645-a7ce-66053f3bdaa7)

I then modified the `Path` (originally, it was `/tv/Erzgebirge Crime Story`, but I took the screenshot above **after** already changing it

![Image](https://github.com/user-attachments/assets/57a77205-16a0-4151-b4d7-6b275865eb54)

Now the program downloaded the files like this; the files with red `size` value have been completed (they play via `mpv` right until the end)

![Image](https://github.com/user-attachments/assets/2e130577-fab0-4d5b-8bd6-1880f4931135)

According to sonaarr, the episodes are missing from disk

![Image](https://github.com/user-attachments/assets/01afd1d4-787c-4d62-a7b9-477b41356c8f)

I manually ran `refresh & scan`. 

# Question

Should these episodes not have been moved to `/tv/Erzgebirgskrimi (2019)` in my **media archive**? Instead, they reside in `/volume1/secure/downloads/sabnzbd/complete/mediathek/tv` (**no** subfolder for series name or season).

Of course, I can now manually move the files, but tbh. I assumed that an sonarr integration would automatically do this (or rather, **sonarr** would treat this as any other download, thus move the files where they belong).

Is there some sort of error on my part, or is this expected behavior?

Thank you in advance for your reply :) Even if I have to manually move the files, this project is already a great addition to my stack

**Comment by prankousky** [comment]
Small update: after **manually** moving the files, then performing another `refresh & scan`, the episodes have been recognized:

![Image](https://github.com/user-attachments/assets/e465acb4-b418-4422-8f2f-74090a782c3b)

**Comment by PCJones** [comment]
Hi,

please use the beta branch and config as recommended and report back if it will solve the problem :)
https://github.com/PCJones/MediathekArr/releases/tag/v1.0-beta

**Comment by prankousky** [comment]
Thank you.

I have switched to beta with the configuration pasted below. Now, during download, the folder structure looks like this (this is actually **while** `sonarr` was processing the file; so this screenshot was taken while the file was moved from incomplete to complete, just fyi)

![Image](https://github.com/user-attachments/assets/ad2916f4-bd42-4d6c-a318-2c71a3f110cf)

Then, once downloaded, it changes to this

![Image](https://github.com/user-attachments/assets/30249767-c42b-43c4-98a6-0047799f7c6b)

(weird: the `*.srt` file is gone. Would be a nice touch to keep it in case somebody needs subtitles)

`sonarr` shows this error about that particular file

![Image](https://github.com/user-attachments/assets/0c77c108-9fbc-4235-bd72-d24c1ac83452)

Relevant `docker-compose.yml` part:

**NOTES**: `1024` is my `root` user; is this correct? When it was set to `1038` (my regular user), there was something in the logs about not having permissions to the specified folders, so I changed to this. This issue was even there when I `chmod -R 0777` those folders, which feels weird to me... shouldn't that mean **any** user can write to them? Why do I need to run the container as root user?

```yml
  mediathekarr:
    image: pcjones/mediathekarr:beta
    restart: unless-stopped
    container_name: mediathekarr
    environment:
      - PUID=1024
      - PGID=1024
      - TZ=Europe/Berlin
      # You can use the web interface at http://localhost:5007 to configure the following settings
      # Alternatively, you can set them here
      #- DOWNLOAD_INCOMPLETE_PATH=/data/mediathek/incomplete # Path to incomplete downloads
      #- DOWNLOAD_COMPLETE_PATH=/data/mediathek/complete # Path to complete downloads"

      # Only change this if you are hosting your own API. Not needed for 99% of users
      - MEDIATHEKARR_API_BASE_URL=https://mediathekarr.pcjones.de/api/v1
    volumes:
      - /volume2/securexxl/services/docker/config/mediathekarr:/app/config
      - /volume1/secure/downloads/sabnzbd/complete/mediathek/complete:/data/mediathek/complete
      - /volume1/secure/downloads/sabnzbd/complete/mediathek/incomplete:/data/mediathek/incomplete
    ports:
      - "127.0.0.1:5007:5007" # Port on the right side can be changed to any value you like
```

Sorry, but I have one more question: what would one have to do in order to **not** use your api for `MEDIATHEKARR_API_BASE_URL`? I don't mind using it at all, but what if your domain was ever down, or you decided that you didn't want to host the api any longer? In this case, it'd be nice to still be able to use this project.
(I am just OCD about my self-hosted projects not depending on external sources like this once they are set up)

Thank you :)
