### ISSUE TITLE
Install using Docker - guide

### ISSUE THREAD

**Issue by BulldozerPete** [PCJones/MediathekArr#5]
Hello,

I would really like to use this app but don't know how to integrate this into my LSIO container pool.
1. Do I need to install SABnzbd besides Prowlarr and Sonarr?
2. I have applied the [Consistent and well planned paths](https://wiki.servarr.com/docker-guide#consistent-and-well-planned-paths). What path do I need to setup in MediathekArr (DOWNLOAD_FOLDER_PATH_MAPPING=/downloads/completed)?

Thank you for your feedback.

**Comment by Subito** [comment]
Hi!

the value of `DOWNLOAD_FOLDER_PATH_MAPPING` should be the path Sonarr expects. Probably something starting with `/data` if you followed the guides. Whereever you put the downloads for Sonarr to import.

And then under `volumes:`, change `./your_temp_downloads_folder` to the path where the downloads should be stored. For example if sonarr has the volume `/mnt/media:/data`, set `DOWNLOAD_FOLDER_PATH_MAPPING=/data/downloads` and the volume `/mnt/media/downloads:/app/downloads` in mediathekarr.

Hope this helps.

**Comment by PCJones** [comment]
Hi!

SABnzbd is not needed. MediathekArrs download clients imitates SABnzbd so that it can be integrated into Sonarr/Radarr.

Can you share your existing docker volume mounts for sonarr? I know the current docker compose of MediathekArr is confusing, I'm looking for better ways to do it haha

**Comment by BulldozerPete** [comment]
Sonarr volume mounts:

`    volumes:
      - /mnt/sonarr/data:/config
      - /mnt/data/:/data`

**Comment by BulldozerPete** [comment]
Dosen't work with that:

```
services:
  mediathekarr:
    image: pcjones/mediathekarr:latest
    container_name: mediathekarr
    environment:
      - TZ=Europe/Berlin
      - DOWNLOAD_FOLDER_PATH_MAPPING=/mnt/data/ # Change right side for correct path mapping
      # - MEDIATHEKARR_API_BASE_URL=https://mediathekarr.pcjones.de/api/v1 # Only change this if you are hosting your own API. Not needed for 99% of users
    volumes:
      - /mnt/swap/mediathek/downloads:/app/downloads      # Change left side to your temp download folder location
    ports:
      - "127.0.0.1:5007:5007"                             # Port can be changed
    restart: unless-stopped
```

**Comment by PCJones** [comment]
So Sonarr has no way to access the download folder of mediathekarr?

If you map the download folder to this:
`- /mnt/swap/mediathek/downloads:/app/downloads `
then Sonarr needs to be able to see `/mnt/swap/mediathek/downloads` somehow.

For example, add this do your Sonarr volume mounts:
`- /mnt/swap/mediathek/downloads:/mediathek/downloads`

And then use this mediathekarr config:
```
services:
  mediathekarr:
    image: pcjones/mediathekarr:latest
    container_name: mediathekarr
    environment:
      - TZ=Europe/Berlin
      - DOWNLOAD_FOLDER_PATH_MAPPING=/mediathek/downloads # Change right side for correct path mapping
    volumes:
      - /mnt/swap/mediathek/downloads:/app/downloads      # Change left side to your temp download folder location
    ports:
      - "127.0.0.1:5007:5007"                             # Port can be changed
    restart: unless-stopped
```
