### ISSUE TITLE
Sudden Error with Prowlarr: Indexer API call resulted in an unexpected StatusCode [BadRequest]: Property Name: "" Attempted Value: ""

### ISSUE THREAD

**Issue by norgur** [PCJones/MediathekArr#52]
Hi,

I'm very suddenly getting the error posted above when trying to use Mediathekarr with Prowlarr. I'm stumped, since the config was working before. I

Log from the container when I tested the connection with Prowlarr:

```
`[MediathekArrDownloader] info: Program - Incoming Request: GET /api?t=search&extended=1

[MediathekArrDownloader] info: System.Net.Http.HttpClient.Default.LogicalHandler - Start processing HTTP request GET http://localhost:5008/api/?*

[MediathekArrDownloader] info: System.Net.Http.HttpClient.Default.ClientHandler - Sending HTTP request GET http://localhost:5008/api/?*

[MediathekArrServer] info: System.Net.Http.HttpClient.Default.LogicalHandler - Start processing HTTP request GET https://mediathekarr.pcjones.de/api/v1/get_show.php?*

[MediathekArrServer] info: System.Net.Http.HttpClient.Default.ClientHandler - Sending HTTP request GET https://mediathekarr.pcjones.de/api/v1/get_show.php?*

[MediathekArrServer] info: System.Net.Http.HttpClient.Default.ClientHandler - Received HTTP response headers after 302.521ms - 200

[MediathekArrServer] info: System.Net.Http.HttpClient.Default.LogicalHandler - End processing HTTP request after 302.6989ms - 200

[MediathekArrDownloader] info: System.Net.Http.HttpClient.Default.ClientHandler - Received HTTP response headers after 306.0709ms - 400

[MediathekArrDownloader] info: System.Net.Http.HttpClient.Default.LogicalHandler - End processing HTTP request after 307.7257ms - 400

[MediathekArrDownloader] info: System.Net.Http.HttpClient.Default.ClientHandler - Received HTTP response headers after 351.2129ms - 400

[MediathekArrDownloader] info: System.Net.Http.HttpClient.Default.LogicalHandler - End processing HTTP request after 351.4002ms - 400

[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=queue&start=0&limit=0&category=tv&apikey=x&output=json

[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=history&start=0&limit=60&category=tv&apikey=x&output=json

[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=queue&start=0&limit=0&category=movies&apikey=21&output=json

[MediathekArrDownloader] info: Program - Incoming Request: GET /download/api?mode=history&start=0&limit=60&category=movies&apikey=21&output=json`
```

Docker-Compose:

```
  mediathekarr:
    image: pcjones/mediathekarr:beta
    container_name: mediathekarr
    environment:
      - TZ=Europe/Berlin
      - PUID=13011
      - PGID=13000
      - UMASK=002
    ports:
      - 5217:5007
    volumes:
      -./mediathek:/data/mediathek
      - ./mediathekarr-config:/app/config
    restart: unless-stopped
```
