### ISSUE TITLE
ARM build

### ISSUE THREAD

**Issue by PCJones** [PCJones/MediathekArr#6]

**Comment by BulldozerPete** [comment]
Any update?

**Comment by PCJones** [comment]
> Any update?

Will come with 1.0 release

**Comment by PCJones** [comment]
If you have git on your system you can already test the arm build:

```
services:
  mediathekarr:
    build:
      context: https://github.com/PCJones/MediathekArr.git#v2
      dockerfile: Dockerfile.arm64
    restart: unless-stopped
    container_name: mediathekarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      # You can use the web interface at http://localhost:5007 to configure the following settings
      # Alternatively, you can set them here
      #- DOWNLOAD_INCOMPLETE_PATH=/data/mediathek/incomplete # Path to incomplete downloads
      #- DOWNLOAD_COMPLETE_PATH=/data/mediathek/complete # Path to complete downloads"
      #- CATEGORIES=tv,movies,sonarr_blackhole,radarr_blackhole # Comma separated list of categories to expose

      # Only change this if you are hosting your own API. Not needed for 99% of users
      - MEDIATHEKARR_API_BASE_URL=https://mediathekarr.pcjones.de/api/v1
    volumes:
      - /docker/appdata/mediathekarr:/app/config
      - /data/mediathek/complete:/data/mediathek/complete
      - /data/mediathek/incomplete:/data/mediathek/incomplete
    ports:
      - "127.0.0.1:5007:5007" # Port on the right side can be changed to any value you like
```
